# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on a macOS system.
stages:
  - build
  - test
  - archive
  - deploy

build_project:
  stage: build
  script:
    - xcodebuild clean -project AASwiftSDK.xcodeproj -scheme SchemeName | xcpretty
    - xcodebuild test -project AASwiftSDK.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' | xcpretty -s

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/AASwiftSDK -scheme SchemeName
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/AASwiftSDK.xcarchive" -exportPath "build/AASwiftSDK.ipa" -exportProvisioningProfile "ProvisioningProfileName"
  only:
    - master
  artifacts:
    paths:
      - build/AASwiftSDK.ipa
  tags:
    - ios_11-3
    - xcode_9-3
    - macos_10-13
